### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by ayushfreak**

### CODE REVIEW

**Comment by shubham-barudwale** [comment]
Hello @ayushfreak! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`test/test_pyre/test.py`](https://github.com/ayushfreak/action/blob/0f76045fb9d65ec033fd8e1c2ff6ce96557997e6/test/test_pyre/test.py):

> [Line 11:1](https://github.com/ayushfreak/action/blob/0f76045fb9d65ec033fd8e1c2ff6ce96557997e6/test/test_pyre/test.py#L11): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 13:5](https://github.com/ayushfreak/action/blob/0f76045fb9d65ec033fd8e1c2ff6ce96557997e6/test/test_pyre/test.py#L13): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

**Comment by shubham-barudwale** [comment]
Hello @ayushfreak! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`test/test_pyre/test.py`](https://github.com/ayushfreak/action/blob/0f76045fb9d65ec033fd8e1c2ff6ce96557997e6/test/test_pyre/test.py):

> [Line 11:1](https://github.com/ayushfreak/action/blob/0f76045fb9d65ec033fd8e1c2ff6ce96557997e6/test/test_pyre/test.py#L11): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 13:5](https://github.com/ayushfreak/action/blob/0f76045fb9d65ec033fd8e1c2ff6ce96557997e6/test/test_pyre/test.py#L13): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

**Comment by shubham-barudwale** [comment]
Hello @ayushfreak! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`test/test_pyre/test.py`](https://github.com/ayushfreak/action/blob/0f76045fb9d65ec033fd8e1c2ff6ce96557997e6/test/test_pyre/test.py):

> [Line 11:1](https://github.com/ayushfreak/action/blob/0f76045fb9d65ec033fd8e1c2ff6ce96557997e6/test/test_pyre/test.py#L11): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 13:4](https://github.com/ayushfreak/action/blob/0f76045fb9d65ec033fd8e1c2ff6ce96557997e6/test/test_pyre/test.py#L13): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'b'
> [Line 13:5](https://github.com/ayushfreak/action/blob/0f76045fb9d65ec033fd8e1c2ff6ce96557997e6/test/test_pyre/test.py#L13): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

**Comment by shubham-barudwale** [comment]
Hello @ayushfreak! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`test/test_pyre/test.py`](https://github.com/ayushfreak/action/blob/0f76045fb9d65ec033fd8e1c2ff6ce96557997e6/test/test_pyre/test.py):

> [Line 11:1](https://github.com/ayushfreak/action/blob/0f76045fb9d65ec033fd8e1c2ff6ce96557997e6/test/test_pyre/test.py#L11): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 13:5](https://github.com/ayushfreak/action/blob/0f76045fb9d65ec033fd8e1c2ff6ce96557997e6/test/test_pyre/test.py#L13): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

**Comment by ayushfreak** [comment]
@pep8speaks pep8ify

**Comment by ayushfreak** [comment]
@pep8speaks pep8ify

**Comment by shubham-barudwale** [comment]
Hello @ayushfreak! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`test/test_pyre/test.py`](https://github.com/ayushfreak/action/blob/0f76045fb9d65ec033fd8e1c2ff6ce96557997e6/test/test_pyre/test.py):

> [Line 11:1](https://github.com/ayushfreak/action/blob/0f76045fb9d65ec033fd8e1c2ff6ce96557997e6/test/test_pyre/test.py#L11): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 13:5](https://github.com/ayushfreak/action/blob/0f76045fb9d65ec033fd8e1c2ff6ce96557997e6/test/test_pyre/test.py#L13): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

**Comment by ayushfreak** [comment]
@pep8speaks suggest diff

**Comment by ayushfreak** [comment]
@pep8speaks Suggest a diff

**Pull request closed without merging**
